default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  # No Render, este arquivo será criado no disco efêmero
  # e apagado quando o servidor reiniciar. Perfeito para seu uso.
  database: storage/production.sqlite3