default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  # O Rails 8 exige que definamos estas chaves separadas
  primary:
    <<: *default
    database: storage/production.sqlite3
  cache:
    <<: *default
    database: storage/production.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/production.sqlite3
    migrations_paths: db/cable_migrate